version: '3.7'
services:
  elasticsearchsource:
    image: 'docker.elastic.co/elasticsearch/elasticsearch-oss:6.8.23'
    networks:
      - migrations
    environment:
      - discovery.type=single-node
      - path.repo=/snapshots
    ports:
      - '19200:9200'
    volumes:
      - ./snapshots:/snapshots

  opensearchtarget:
    image: 'opensearchproject/opensearch:2.11.1'
    environment:
      - discovery.type=single-node
      - plugins.security.disabled=true
    networks:
      - migrations
    ports:
      - "29200:9200"

networks:
  migrations:
    driver: bridge
